### ISSUE TITLE
红色数据用IC表示，蓝色数据用OC表示？

### ISSUE THREAD

**Issue by RZH0910** [flymin/vgg16-on-Zynq#1]
您好，请问，红色数据用IC表示，蓝色数据用OC表示，黄色数据用S表示，绿色数据用R表示，灰色数据用L表示；
这里以及后面的计算单元复用的相关分析计算，这些参数是什么意思啊？

**Comment by flymin** [comment]
报告是 pdf，转到 markdown 有些格式丢了。如果需要 pdf 的话请 email: 905370712@qq.com
